# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XXProjectNew' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XXProjectNew
  
  
  pod 'RongCloudIM/IMLib', '2.8.0'
  pod 'RongCloudIM/IMKit', '2.8.0'

  target 'XXProjectNewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XXProjectNewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
